version: "3"

services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GRUP_ID: ${GRUP_ID}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./sbase:/SeleniumBase/sbase:z
